const classes = [
  { id: 'oct-17', date: 'Friday, October 17', title: 'Pet First Aid & CPR', time: '10:00 AM – 2:00 PM', place: 'Community Learning Center', seats: 12, price: 89 },
  { id: 'nov-8', date: 'Saturday, November 8', title: 'Pet First Aid & CPR', time: '9:30 AM – 1:30 PM', place: 'Northside Community Hall', seats: 16, price: 89 },
  { id: 'dec-6', date: 'Saturday, December 6', title: 'Pet First Aid Essentials', time: '10:00 AM – 1:00 PM', place: 'Community Learning Center', seats: 14, price: 69 }
];
const sampleRegistrations = [
  ['ava.martin@example.com', 'Ava', 'Martin', 'english', 'Pet First Aid & CPR'], ['liam.brown@example.com', 'Liam', 'Brown', 'english', 'Pet First Aid & CPR'], ['maya.chen@example.com', 'Maya', 'Chen', 'english', 'Pet First Aid & CPR'], ['noah.davis@example.com', 'Noah', 'Davis', 'english', 'Pet First Aid & CPR'], ['zoe.green@example.com', 'Zoe', 'Green', 'english', 'Pet First Aid & CPR'], ['leo.wilson@example.com', 'Leo', 'Wilson', 'english', 'Pet First Aid & CPR'], ['emma.jones@example.com', 'Emma', 'Jones', 'english', 'Pet First Aid & CPR']];
let activeClass;
const registrations = () => JSON.parse(localStorage.getItem('ppaRegistrations') || '[]');
const saveRegistrations = items => localStorage.setItem('ppaRegistrations', JSON.stringify(items));
const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));

document.getElementById('class-list').innerHTML = classes.map(course => `<article class="class-card"><p class="date-label">${course.date}</p><h3>${course.title}</h3><p class="class-meta">${course.time}<br>${course.place}<br>${course.seats} seats available</p><p><strong>$${course.price}</strong> per student</p><button class="button register-button" data-class="${course.id}">Select this class</button></article>`).join('');
document.getElementById('year').textContent = new Date().getFullYear();

const modal = document.getElementById('registration');
function openRegistration(id) { activeClass = classes.find(course => course.id === id); modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); showForm(); }
function closeRegistration() { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); }
function showForm() { document.getElementById('registration-content').innerHTML = `<p class="eyebrow">Reserve your place</p><h2 id="registration-title">${activeClass.title}</h2><p>${activeClass.date} · ${activeClass.time}<br>${activeClass.place} · $${activeClass.price} per student</p><form id="registration-form"><div class="form-grid"><label>Email*<input name="email" type="email" required autocomplete="email"></label><label>First name*<input name="firstName" required autocomplete="given-name"></label><label>Last name*<input name="lastName" required autocomplete="family-name"></label><label>Language<select name="language"><option value="english">English</option><option value="spanish">Spanish</option><option value="french">French</option><option value="other">Other</option></select></label></div><fieldset><legend>Would you like to add a pet first aid kit?</legend><label class="radio-option"><input type="radio" name="kit" value="no" checked><span><strong>No kit</strong>Course registration only · $${activeClass.price}</span></label><label class="radio-option"><input type="radio" name="kit" value="yes"><span><strong>Add a first aid kit</strong>Course + kit · $${activeClass.price + 34}</span></label></fieldset><button class="button" type="submit">Continue to demo checkout</button><p class="form-note">This is a demo checkout. Payments and registration storage will be connected securely before launch.</p></form>`;
  document.getElementById('registration-form').addEventListener('submit', submitRegistration);
}
function submitRegistration(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); const all = registrations(); all.push({...data, classTitle: activeClass.title, classDate: activeClass.date}); saveRegistrations(all); document.getElementById('registration-content').innerHTML = `<div class="confirmation"><div class="success">✓</div><p class="eyebrow">Demo checkout complete</p><h2>You’re on the list!</h2><p>Thanks, ${escapeHtml(data.firstName)}. In the live site, Stripe will securely take payment and send an email confirmation here.</p><button class="button" data-close>Done</button></div>`; renderDashboard(); }
document.addEventListener('click', event => { const button = event.target.closest('.register-button'); if (button) openRegistration(button.dataset.class); if (event.target.closest('[data-close]')) closeRegistration(); });
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeRegistration(); });

function allRegistrations() { return [...sampleRegistrations.map(([email, firstName, lastName, language, classTitle]) => ({email, firstName, lastName, language, classTitle})), ...registrations()]; }
function renderDashboard() { const items = allRegistrations(); document.getElementById('registration-count').textContent = items.length; document.getElementById('registrant-table').innerHTML = items.map(item => `<tr><td>${escapeHtml(item.firstName)} ${escapeHtml(item.lastName)}</td><td>${escapeHtml(item.email)}</td><td>${escapeHtml(item.language)}</td><td>${escapeHtml(item.classTitle)}</td></tr>`).join(''); }
renderDashboard();
document.getElementById('login-form').addEventListener('submit', event => { event.preventDefault(); document.getElementById('admin-login').classList.add('hidden'); document.getElementById('dashboard').classList.remove('hidden'); renderDashboard(); });
document.getElementById('log-out').addEventListener('click', () => { document.getElementById('dashboard').classList.add('hidden'); document.getElementById('admin-login').classList.remove('hidden'); });
document.getElementById('download-csv').addEventListener('click', () => { const rows = allRegistrations().map(item => [item.email, item.firstName, item.lastName, item.language]); const csv = [['Email*', 'First Name*', 'Last Name*', 'Language'], ...rows].map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\r\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], {type: 'text/csv'})); link.download = 'protrainings-registrations.csv'; link.click(); URL.revokeObjectURL(link.href); });
const menuButton = document.querySelector('.menu-button'); const nav = document.querySelector('.site-nav'); menuButton.addEventListener('click', () => { const open = nav.classList.toggle('open'); menuButton.setAttribute('aria-expanded', open); });
